# GitHub Actions workflow to automatically update economic data
# This workflow can be run manually or scheduled to run periodically

name: Update Economic Data

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Uncomment the following lines to run automatically on a schedule
  # schedule:
  #   # Run on the 17th and 1st of each month at 9 AM UTC
  #   # Note: Zillow updates ZHVI data on the 16th, so we run on the 17th
  #   - cron: '0 9 1,17 * *'

jobs:
  update-economic-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Test data update scripts
        run: |
          npm run test-bls
          npm run test-zhvi
        
      - name: Update BLS wage data
        run: npm run update-bls
        
      - name: Update ZHVI housing data
        run: npm run update-zhvi
        
      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
            # Show what changed
            echo "Changed files:"
            git diff --name-only
          fi
          
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/components/PEGraph/data/bls-wages.ts
          git add src/components/PEGraph/data/avl-county-zhvi.json
          git add src/components/PEGraph/data/avl-county-zhvi.csv
          git add src/components/PEGraph/data/County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv
          git commit -m "Auto-update economic data $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
          
      - name: Create summary
        run: |
          if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
            echo "✅ Economic data updated successfully" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Updated Files:" >> $GITHUB_STEP_SUMMARY
            git diff --name-only HEAD~1 | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ No new economic data available" >> $GITHUB_STEP_SUMMARY
          fi
